# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('taste', models.CharField(max_length=200)),
                ('taste_kind', models.CharField(max_length=200)),
                ('img_src', models.ImageField(upload_to=b'')),
            ],
            options={
                'db_table': 'tobacco',
            },
        ),
        migrations.CreateModel(
            name='Tobacco_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('tobacco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco.Tobacco')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tobacco_rating',
            },
        ),
    ]
